# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\find_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FindDialog(object):
    def setupUi(self, FindDialog):
        FindDialog.setObjectName("FindDialog")
        FindDialog.resize(458, 250)
        FindDialog.setMinimumSize(QtCore.QSize(0, 250))
        FindDialog.setMaximumSize(QtCore.QSize(16777215, 250))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FindDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(FindDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.whatLabel = QtWidgets.QLabel(FindDialog)
        self.whatLabel.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.whatLabel.setObjectName("whatLabel")
        self.horizontalLayout.addWidget(self.whatLabel)
        self.findLineEdit = QtWidgets.QLineEdit(FindDialog)
        self.findLineEdit.setObjectName("findLineEdit")
        self.horizontalLayout.addWidget(self.findLineEdit)
        self.findPushButton = QtWidgets.QPushButton(FindDialog)
        self.findPushButton.setMinimumSize(QtCore.QSize(110, 0))
        self.findPushButton.setObjectName("findPushButton")
        self.horizontalLayout.addWidget(self.findPushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backDirectionBox = QtWidgets.QCheckBox(FindDialog)
        self.backDirectionBox.setObjectName("backDirectionBox")
        self.horizontalLayout_2.addWidget(self.backDirectionBox)
        spacerItem = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.matchWordBox = QtWidgets.QCheckBox(FindDialog)
        self.matchWordBox.setObjectName("matchWordBox")
        self.horizontalLayout_3.addWidget(self.matchWordBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.matchCaseBox = QtWidgets.QCheckBox(FindDialog)
        self.matchCaseBox.setObjectName("matchCaseBox")
        self.horizontalLayout_4.addWidget(self.matchCaseBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wrapAroundBox = QtWidgets.QCheckBox(FindDialog)
        self.wrapAroundBox.setObjectName("wrapAroundBox")
        self.horizontalLayout_5.addWidget(self.wrapAroundBox)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.countPushButton = QtWidgets.QPushButton(FindDialog)
        self.countPushButton.setMinimumSize(QtCore.QSize(110, 0))
        self.countPushButton.setObjectName("countPushButton")
        self.verticalLayout.addWidget(self.countPushButton)
        self.findAllInDocsPushButton = QtWidgets.QPushButton(FindDialog)
        self.findAllInDocsPushButton.setObjectName("findAllInDocsPushButton")
        self.verticalLayout.addWidget(self.findAllInDocsPushButton)
        self.findAllInCurPushButton = QtWidgets.QPushButton(FindDialog)
        self.findAllInCurPushButton.setMinimumSize(QtCore.QSize(110, 0))
        self.findAllInCurPushButton.setObjectName("findAllInCurPushButton")
        self.verticalLayout.addWidget(self.findAllInCurPushButton)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_6, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(FindDialog)
        self.groupBox.setMinimumSize(QtCore.QSize(150, 0))
        self.groupBox.setObjectName("groupBox")
        self.normalRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.normalRadioButton.setGeometry(QtCore.QRect(11, 21, 82, 17))
        self.normalRadioButton.setObjectName("normalRadioButton")
        self.extendedRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.extendedRadioButton.setGeometry(QtCore.QRect(11, 44, 82, 17))
        self.extendedRadioButton.setObjectName("extendedRadioButton")
        self.reRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.reRadioButton.setGeometry(QtCore.QRect(11, 67, 131, 17))
        self.reRadioButton.setObjectName("reRadioButton")
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(269, 48, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.closePushButton = QtWidgets.QPushButton(FindDialog)
        self.closePushButton.setMinimumSize(QtCore.QSize(110, 0))
        self.closePushButton.setObjectName("closePushButton")
        self.verticalLayout_2.addWidget(self.closePushButton)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 2, 1, 1)

        self.retranslateUi(FindDialog)
        self.closePushButton.clicked.connect(FindDialog.close)
        QtCore.QMetaObject.connectSlotsByName(FindDialog)

    def retranslateUi(self, FindDialog):
        _translate = QtCore.QCoreApplication.translate
        FindDialog.setWindowTitle(_translate("FindDialog", "Find in file(s)"))
        self.whatLabel.setText(_translate("FindDialog", "Find what: "))
        self.findPushButton.setText(_translate("FindDialog", "Find next"))
        self.backDirectionBox.setText(_translate("FindDialog", "Backward direction"))
        self.matchWordBox.setText(_translate("FindDialog", "Match whole word"))
        self.matchCaseBox.setText(_translate("FindDialog", "Match case"))
        self.wrapAroundBox.setText(_translate("FindDialog", "Wrap around"))
        self.countPushButton.setText(_translate("FindDialog", "Count"))
        self.findAllInDocsPushButton.setText(_translate("FindDialog", "Find all\n"
"in opened documents"))
        self.findAllInCurPushButton.setText(_translate("FindDialog", "Find All in Current \n"
"Document"))
        self.groupBox.setTitle(_translate("FindDialog", "Search Mode"))
        self.normalRadioButton.setText(_translate("FindDialog", "Normal"))
        self.extendedRadioButton.setText(_translate("FindDialog", "Extended"))
        self.reRadioButton.setText(_translate("FindDialog", "Regular Expression"))
        self.closePushButton.setText(_translate("FindDialog", "Close"))

import rdfnavigator_rc
